### ISSUE TITLE
BOM - capacitors

### ISSUE THREAD

**Issue by VisionOneSrl** [GuitarML/FunBox#1]
I'm trying to build a funbox and I've a problem with the bom

https://github.com/GuitarML/FunBox/blob/main/hardware/funbox_v3_midi_exp/funbox_v3_BOM.csv

the item 2, C1 and C2 capacitors has a value of 100 but is not specified unit of measure in Farad. 
Also how can I know if a capacitor is electrolitic, polyester o ceramic?

**Comment by GuitarML** [comment]
It's 100pF, I will update the BOM with units and type, thanks!
