### ISSUE TITLE
Mars models and IRs

### ISSUE THREAD

**Issue by xconverge** [GuitarML/FunBox#5]
Hey @GuitarML, thanks for the project! I am wondering if you have any further documentation/comments about how the IRs and models were created for the mars project. (ir_data.h and all_model_data_gru9_4count.h)

I have everything more or less setup but want to use my own chosen IRs/models and understand that process completely

(I am pretty up to speed for the most part with the codebase and c++ so feel free to be as technical as you want)

Looks like some good reading/poking around for the models would be here https://github.com/GuitarML/ToneLibrary/

**Comment by xconverge** [comment]
I did enough reading in your other repositories to get a better idea of it

**Comment by xconverge** [comment]
@GuitarML so I found a lot across your repos for the model as mentioned, but I can't find much about how the IRs were generated, I assume they are a .wav to txt conversion, anything to keep in mind for this?

**Comment by GuitarML** [comment]
That’s exactly it, it’s the raw IR data converted to text and put into the .h header file. I also had shorten them a lot by trimming the end off, or else the Daisy seed couldn’t keep up with processing.
